export const foods = [
  {
    id: 1,
    meal: "Breackfast",
    img: "ximg_1.jpg",
    name: "Italian Sauce Mushroom",
    price: "$19.00",
  },
  {
    id: 2,
    meal: "Breackfast",
    img: "ximg_2.jpg",
    name: "Salted Fried Chicken",
    price: "$19.00",
  },
  {
    id: 3,
    meal: "Breackfast",
    img: "ximg_3.jpg",
    name: "Italian Sauce Mushroom",
    price: "$19.00",
  },
  {
    id: 4,
    meal: "Breackfast",
    img: "ximg_4.jpg",
    name: "Italian Sauce Mushroom",
    price: "$19.00",
  },
  {
    id: 5,
    meal: "Lunch",
    img: "ximg_1_b.jpg",
    name: "Italian Sauce Mushroom",
    price: "$16.00",
  },
  {
    id: 6,
    meal: "Lunch",
    img: "ximg_2_b.jpg",
    name: "Salted Fried Chicken",
    price: "$15.00",
  },
  {
    id: 7,
    meal: "Lunch",
    img: "ximg_3_b.jpg",
    name: "Italian Sauce Mushroom",
    price: "$30.00",
  },
  {
    id: 8,
    meal: "Lunch",
    img: "ximg_4_b.jpg",
    name: "Italian Sauce Mushroom",
    price: "$40.00",
  },
  {
    id: 9,
    meal: "Dinner",
    img: "ximg_1_n.jpg",
    name: "Italian Sauce Mushroom",
    price: "$10.00",
  },
  {
    id: 10,
    meal: "Dinner",
    img: "ximg_2_n.jpg",
    name: "Salted Fried Chicken",
    price: "$20.00",
  },
  {
    id: 11,
    meal: "Dinner",
    img: "ximg_1_n.jpg",
    name: "Italian Sauce Mushroom",
    price: "$25.00",
  },
  {
    id: 12,
    meal: "Dinner",
    img: "ximg_4.jpg",
    name: "Italian Sauce Mushroom",
    price: "$27.00",
  },
  {
    id: 13,
    meal: "Drinks",
    img: "ximg_1_d.jpg",
    name: "Italian Sauce Mushroom",
    price: "$19.00",
  },
  {
    id: 14,
    meal: "Drinks",
    img: "ximg_2_d.jpg",
    name: "Salted Fried Chicken",
    price: "$19.00",
  },
  {
    id: 15,
    meal: "Drinks",
    img: "ximg_3_d.jpg",
    name: "Italian Sauce Mushroom",
    price: "$19.00",
  },
  {
    id: 16,
    meal: "Drinks",
    img: "ximg_4_d.jpg",
    name: "Italian Sauce Mushroom",
    price: "$19.00",
  },
];
export const desserts = [
  {
    id: 1,
    img: "xdessert_1.png",
    name: "Cherry Muffin",
    price: "$20",
  },
  {
    id: 2,
    img: "xdessert_2.png",
    name: "Rose Muffin",
    price: "$20",
  },
  {
    id: 3,
    img: "xdessert_5.png",
    name: "Sweet Donut",
    price: "$20",
  },
  {
    id: 4,
    img: "xdessert_4.png",
    name: "Choco Cake",
    price: "$20",
  },
];
